import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Provider from "./provider";
import {
  CHAMPION_PAGE,
  HOME_PAGE,
  ITEM_PAGE,
  ROTATION_PAGE,
} from "@/constants";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "리그 오브 레전드 정보 앱",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-around bg-darkblue text-white py-3">
          <Link href={HOME_PAGE}>홈</Link>
          <Link href={CHAMPION_PAGE}>챔피언 목록</Link>
          <Link href={ITEM_PAGE}>아이템 목록</Link>
          <Link href={ROTATION_PAGE}>챔피언 로테이션</Link>
        </header>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
